sudo: required
services:
  - docker

before_install:
 - docker build -t ankhomenko/docker-guide -f Dockerfile.dev .
 
script:
 - docker run ankhomenko/docker-guide npm run test -- --coverage

 deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-tackling"
  env: "DockerTackling-env"
  bucket_name: "elasticbeanstalk-eu-central-1-660271560963"
  bucket_path: "docker-tackling"
  on:
    branch: master
  access_key_id: $aws_ACCESS_KEY
  secret_access_key:
    secure: "$aws_SECRET_KEY"


